- name: create and copy the install script
  template:
    src: "common/install-vm.sh"
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-create-vm.sh"
    owner: root
    group: root
    mode: 0770
  delegate_to: "{{ hyper }}"

- name: copy unattended autoinstall xml file
  template:
    src: "{{ distroname }}/autounattend.xml"
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-autounattend.xml"
    owner: root
    group: root
    mode: 0660
  delegate_to: "{{ hyper }}"

- name: copy winrm activation script
  copy:
    src: "windows/ConfigureRemotingForAnsible.ps1"
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-ConfigureRemotingForAnsible.ps1"
    owner: root
    group: root
    mode: 0660
  delegate_to: "{{ hyper }}"

- name: slice unattended autoinstall file
  template:
    src: "{{ distroname }}/create-autounattend-disk.sh"
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-create-autounattend-disk.sh"
    owner: root
    group: root
    mode: 0770
  delegate_to: "{{ hyper }}"

- name: slice unattended autoinstall file
  command: "/bin/bash {{ virtualfilespath }}{{ inventory_hostname }}-create-autounattend-disk.sh"
  delegate_to: "{{ hyper }}"

- name: execute install script
  command: "/bin/bash {{ virtualfilespath }}{{ inventory_hostname }}-create-vm.sh"
  delegate_to: "{{ hyper }}"

- name: wait for vm to install
  local_action: pause minutes={{ vmwaittime }}
