- name: create and copy the install script
  template:
    src: "/home/ansible/.ansible/playbooks/roles/vminstaller/templates/common/install-vm.sh"
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-create-vm.sh"
    owner: root
    group: root
    mode: 0770
  delegate_to: "{{ hyper }}"

- name: copy unattended autoinstall xml file
  template:
    src: "/home/ansible/.ansible/playbooks/roles/vminstaller/templates/{{ distroname }}/autounattend.xml"
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-autounattend.xml"
    owner: root
    group: root
    mode: 0660
  delegate_to: "{{ hyper }}"

- name: copy winrm activation script
  copy:
    src: "/home/ansible/.ansible/playbooks/roles/vminstaller/files/windows/ConfigureRemotingForAnsible.ps1"
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-ConfigureRemotingForAnsible.ps1"
    owner: root
    group: root
    mode: 0660
  delegate_to: "{{ hyper }}"

- name: copy powershell upgrade script
  copy:
    src: "/home/ansible/.ansible/playbooks/roles/vminstaller/files/windows/PowerShellUpgradeTo3.ps1"
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-PowerShellUpgradeTo3.ps1"
    owner: root
    group: root
    mode: 0660
  delegate_to: "{{ hyper }}"

- name: copy unattended autoinstall file
  template:
    src: "/home/ansible/.ansible/playbooks/roles/vminstaller/templates/{{ distroname }}/create-autounattend-disk.sh"
    dest: "{{ virtualfilespath }}{{ inventory_hostname }}-create-autounattend-disk.sh"
    owner: root
    group: root
    mode: 0770
  delegate_to: "{{ hyper }}"

- name: slice unattended autoinstall file
  command: "/bin/bash {{ virtualfilespath }}{{ inventory_hostname }}-create-autounattend-disk.sh"
  delegate_to: "{{ hyper }}"

- name: execute install script
  command: "/bin/bash {{ virtualfilespath }}{{ inventory_hostname }}-create-vm.sh"
  delegate_to: "{{ hyper }}"
